// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.apache.commons.io.FileUtils;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.assertthat.selenium_shutterbug.core.Shutterbug;
import com.assertthat.selenium_shutterbug.utils.web.ScrollStrategy;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;

import java.util.HashMap;
import java.util.List;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
public class ReferralEntry_backup {
  private static WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

	public static final String Path_Screenshots = System.getProperty("user.dir") + "\\";//path for screenshots
	public static String fileSeparator = System.getProperty("file.separator");//used by the screenshot method below
	public static Date date = new Date();//sets a constant test start date to be used in html reports and screenshots folder
	public static DateFormat dateFormat = new SimpleDateFormat("ddMMyy_HHmmss");
	
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "/Users/Bean/Desktop/Selenium/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void adult1() throws Exception {
    String testName = "Adult1";
    String projectName = "MS_Test";
    String screenName;
 	String imagePath = ".." + fileSeparator + "Results_Screenshots" + fileSeparator + projectName + fileSeparator + testName + "_" + dateFormat.format(date);
	ExcelUtil.setExcelFile(ExcelUtil.Path_TestData + ExcelUtil.File_TestData, "adult1");
	int columnLast = ExcelUtil.lastColumn;
	int rowNumbers = ExcelUtil.rowCount;
	System.out.println("rowcount " + rowNumbers + " last column " + columnLast + "test name" + testName);
	String columnResult = dateFormat.format(date);
	ExcelUtil.setCellData(columnResult, 0, columnLast);
    

    driver.get("http://uat.ms-notprod.homeoffice.gov.uk/nrm/start/?token=d1e34e20-70e4-11e9-b4d2-0d6ee01cb6cd&");
    driver.manage().window().setSize(new Dimension(1440, 877));
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "2-FRLocation";
    driver.findElement(By.id("fr-location-wales")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "3-Under18";
    driver.findElement(By.id("pv-under-age-no")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "4-Under18atExploit";
    driver.findElement(By.id("pv-under-age-at-time-of-exploitation-no")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
	driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "5-VictimAccount";
    driver.findElement(By.id("what-happened")).sendKeys("here are some victim account details");
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "6-Where";
    driver.findElement(By.id("where-exploitation-happened-uk")).click();
    driver.findElement(By.id("where-exploitation-happened-uk-city")).sendKeys("Salford");
    driver.findElement(By.id("where-exploitation-happened-uk-region")).sendKeys("Shropshire"); 
    driver.findElement(By.id("where-exploitation-happened-other-uk-other-location")).sendKeys("additional address details");
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "7-currentLocation";
    driver.findElement(By.id("current-pv-location-uk-city")).sendKeys("Luton");
    driver.findElement(By.id("current-pv-location-uk-region")).sendKeys("Bedfordshire");
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "8-Exploiter";
    driver.findElement(By.id("who-exploited-pv")).click();
    driver.findElement(By.id("who-exploited-pv")).sendKeys("here are some details on the exploiters");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "9-Exploitation";
    driver.findElement(By.id("types-of-exploitation-forced-to-work")).click();
    driver.findElement(By.id("types-of-exploitation-wages-taken")).click();
    driver.findElement(By.id("types-of-exploitation-forced-to-commit-fraud")).click();
    driver.findElement(By.id("types-of-exploitation-prostitution")).click();
    driver.findElement(By.id("types-of-exploitation-child-exploitation")).click();
    driver.findElement(By.id("types-of-exploitation-taken-somewhere")).click();
    driver.findElement(By.id("types-of-exploitation-forced-to-commit-crime")).click();
    driver.findElement(By.id("types-of-exploitation-organs-removed")).click();
    driver.findElement(By.id("types-of-exploitation-unpaid-household-work")).click();
    driver.findElement(By.id("types-of-exploitation-other")).click();
    driver.findElement(By.id("other-exploitation-details")).click();
    driver.findElement(By.id("other-exploitation-details")).sendKeys("another exploitation"); 
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "10-OtherPV";
    driver.findElement(By.id("any-other-pvs-yes")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "11-PoliceReport";
    driver.findElement(By.id("reported-to-police-yes")).click();
    driver.findElement(By.id("reported-to-police-police-forces")).click();
    driver.findElement(By.id("reported-to-police-police-forces")).sendKeys("Police Scotland");
    driver.findElement(By.id("reported-to-police-crime-reference")).click();
    driver.findElement(By.id("reported-to-police-crime-reference")).sendKeys("scot/333/re4");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "12-NRMorDtN";
    driver.findElement(By.id("pv-want-to-submit-nrm-yes")).click();
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "13-PVSupport";
    driver.findElement(By.id("does-pv-need-support-yes")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "14-PVName";
    driver.findElement(By.id("pv-name-first-name")).sendKeys("john");
    driver.findElement(By.id("pv-name-last-name")).sendKeys("green");
    driver.findElement(By.id("pv-name-nickname")).sendKeys("greeno");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "15-PVDoB";
    driver.findElement(By.id("pv-dob-day")).sendKeys("21");
    driver.findElement(By.id("pv-dob-month")).sendKeys("02");
    driver.findElement(By.id("pv-dob-year")).sendKeys("1987");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "16-PVGender";
    driver.findElement(By.id("pv-gender-male")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "17-PVChildren";
    driver.findElement(By.id("does-pv-have-children-yes")).click();
    driver.findElement(By.id("does-pv-have-children-yes-amount")).click();
    driver.findElement(By.id("does-pv-have-children-yes-amount")).sendKeys("2");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "18-PVNationality";
    driver.findElement(By.id("pv-nationality")).click();
    driver.findElement(By.id("pv-nationality")).sendKeys("Yemeni");
    //driver.findElement(By.cssSelector(".govuk-details__summary-text")).click();
    //driver.findElement(By.id("pv-nationality-second")).click();
    //driver.findElement(By.id("pv-nationality-second")).sendKeys("East Timorese");
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "19-PVInterpreter";
    driver.findElement(By.id("pv-interpreter-requirements-yes")).click();
    driver.findElement(By.id("pv-interpreter-requirements-language")).click();
    driver.findElement(By.id("pv-interpreter-requirements-language")).sendKeys("spanish");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "20-Communication";
    driver.findElement(By.id("pv-other-help-with-communication-yes")).click();
    driver.findElement(By.id("pv-other-help-with-communication-aid")).click();
    driver.findElement(By.id("pv-other-help-with-communication-aid")).sendKeys("sign language");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "21-HORef";
    driver.findElement(By.id("pv-ho-reference-yes")).click();
    driver.findElement(By.id("pv-ho-reference-type")).sendKeys("A1231231");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "21.1-DecisionContact";
    driver.findElement(By.id("who-contact-potential-victim")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "22-PVDetails";
    driver.findElement(By.id("pv-contact-details-email")).click();
    driver.findElement(By.id("pv-contact-details-email-input")).sendKeys("pv@info.com");
    driver.findElement(By.id("pv-contact-details-email-check")).click();
    driver.findElement(By.id("pv-contact-details-post")).click();
    driver.findElement(By.id("pv-contact-details-street")).sendKeys("27 green lanes");
    driver.findElement(By.id("pv-contact-details-town")).sendKeys("london");
    driver.findElement(By.id("pv-contact-details-county")).sendKeys("london");
    driver.findElement(By.id("pv-contact-details-postcode")).sendKeys("nw1 2er");
    driver.findElement(By.id("pv-contact-details-post-check")).click();
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "23-Phone";
    driver.findElement(By.id("pv-phone-number-yes")).click();
    driver.findElement(By.name("pv-phone-number-yes")).sendKeys("0987654321");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "24-Consent";
    driver.findElement(By.id("co-operate-with-police-yes")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "26-FRDetails";
    driver.findElement(By.id("fr-details-first-name")).sendKeys("mary");
    driver.findElement(By.id("fr-details-last-name")).sendKeys("bennett");
    driver.findElement(By.id("fr-details-role")).sendKeys("caseworker");
    driver.findElement(By.id("fr-details-phone")).sendKeys("09372638483");
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "27-Alternate";
    driver.findElement(By.id("fr-alternative-contact")).click();
    driver.findElement(By.id("fr-alternative-contact")).sendKeys("alternate@info.com");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    //need to add the CYA screenshot, referral submission step and success page screenshot 
    //once defect 1030 is fixed
    System.out.println("Test completed");
   
    
  }
  
  @Test
  public void adult2() {
    String testName = "Adult2";
    String projectName = "MS_Test";
    String screenName;
 	String imagePath = ".." + fileSeparator + "Results_Screenshots" + fileSeparator + projectName + fileSeparator + testName + "_" + dateFormat.format(date);
    

    driver.get("http://uat.ms-notprod.homeoffice.gov.uk/nrm/start/?token=d95f8100-70e4-11e9-b4d2-0d6ee01cb6cd&");
    driver.manage().window().setSize(new Dimension(1440, 877));
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "2-FRLocation";
    driver.findElement(By.id("fr-location-england")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "3-Under18";
    driver.findElement(By.id("pv-under-age-no")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "4-Under18atExploit";
    driver.findElement(By.id("pv-under-age-at-time-of-exploitation-yes")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
	driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "5-VictimAccount";
    driver.findElement(By.id("what-happened")).sendKeys("here are some victim account details");
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "6-Where";
    driver.findElement(By.id("where-exploitation-happened-uk")).click();
    driver.findElement(By.id("where-exploitation-happened-uk-city")).sendKeys("Bristol");
    driver.findElement(By.id("where-exploitation-happened-uk-region")).sendKeys("Somerset"); 
    driver.findElement(By.id("where-exploitation-happened-other-uk-other-location")).sendKeys("additional address details");
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "7-currentLocation";
    driver.findElement(By.id("current-pv-location-uk-city")).sendKeys("Luton");
    driver.findElement(By.id("current-pv-location-uk-region")).sendKeys("Bedfordshire");
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "8-Exploiter";
    driver.findElement(By.id("who-exploited-pv")).click();
    driver.findElement(By.id("who-exploited-pv")).sendKeys("here are some details on the exploiters");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "9-Exploitation";
    driver.findElement(By.id("types-of-exploitation-forced-to-work")).click();
    driver.findElement(By.id("types-of-exploitation-wages-taken")).click();
    driver.findElement(By.id("types-of-exploitation-forced-to-commit-fraud")).click();
    driver.findElement(By.id("types-of-exploitation-prostitution")).click();
    driver.findElement(By.id("types-of-exploitation-child-exploitation")).click();
    driver.findElement(By.id("types-of-exploitation-taken-somewhere")).click();
    driver.findElement(By.id("types-of-exploitation-forced-to-commit-crime")).click();
    driver.findElement(By.id("types-of-exploitation-organs-removed")).click();
    driver.findElement(By.id("types-of-exploitation-unpaid-household-work")).click();
    driver.findElement(By.id("types-of-exploitation-other")).click();
    driver.findElement(By.id("other-exploitation-details")).click();
    driver.findElement(By.id("other-exploitation-details")).sendKeys("another exploitation"); 
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "10-OtherPV";
    driver.findElement(By.id("any-other-pvs-yes")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "11-PoliceReport";
    driver.findElement(By.id("reported-to-police-yes")).click();
    driver.findElement(By.id("reported-to-police-police-forces")).click();
    driver.findElement(By.id("reported-to-police-police-forces")).sendKeys("Police Scotland");
    driver.findElement(By.id("reported-to-police-crime-reference")).click();
    driver.findElement(By.id("reported-to-police-crime-reference")).sendKeys("scot/333/re4");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "12-NRMorDtN";
    driver.findElement(By.id("pv-want-to-submit-nrm-yes")).click();
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "13-PVSupport";
    driver.findElement(By.id("does-pv-need-support-yes")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "14-PVName";
    driver.findElement(By.id("pv-name-first-name")).sendKeys("john");
    driver.findElement(By.id("pv-name-last-name")).sendKeys("green");
    driver.findElement(By.id("pv-name-nickname")).sendKeys("greeno");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "15-PVDoB";
    driver.findElement(By.id("pv-dob-day")).sendKeys("21");
    driver.findElement(By.id("pv-dob-month")).sendKeys("02");
    driver.findElement(By.id("pv-dob-year")).sendKeys("1987");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "16-PVGender";
    driver.findElement(By.id("pv-gender-male")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "17-PVChildren";
    driver.findElement(By.id("does-pv-have-children-yes")).click();
    driver.findElement(By.id("does-pv-have-children-yes-amount")).click();
    driver.findElement(By.id("does-pv-have-children-yes-amount")).sendKeys("2");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "18-PVNationality";
    driver.findElement(By.id("pv-nationality")).click();
    driver.findElement(By.id("pv-nationality")).sendKeys("Yemeni");
    //driver.findElement(By.cssSelector(".govuk-details__summary-text")).click();
    //driver.findElement(By.id("pv-nationality-second")).click();
    //driver.findElement(By.id("pv-nationality-second")).sendKeys("East Timorese");
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "19-PVInterpreter";
    driver.findElement(By.id("pv-interpreter-requirements-yes")).click();
    driver.findElement(By.id("pv-interpreter-requirements-language")).click();
    driver.findElement(By.id("pv-interpreter-requirements-language")).sendKeys("spanish");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "20-Communication";
    driver.findElement(By.id("pv-other-help-with-communication-yes")).click();
    driver.findElement(By.id("pv-other-help-with-communication-aid")).click();
    driver.findElement(By.id("pv-other-help-with-communication-aid")).sendKeys("sign language");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "21-HORef";
    driver.findElement(By.id("pv-ho-reference-yes")).click();
    driver.findElement(By.id("pv-ho-reference-type")).sendKeys("A1231231");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "21.1-DecisionContact";
    driver.findElement(By.id("who-contact-potential-victim")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "22-PVDetails";
    driver.findElement(By.id("pv-contact-details-email")).click();
    driver.findElement(By.id("pv-contact-details-email-input")).sendKeys("pv@info.com");
    driver.findElement(By.id("pv-contact-details-email-check")).click();
    driver.findElement(By.id("pv-contact-details-post")).click();
    driver.findElement(By.id("pv-contact-details-street")).sendKeys("27 green lanes");
    driver.findElement(By.id("pv-contact-details-town")).sendKeys("london");
    driver.findElement(By.id("pv-contact-details-county")).sendKeys("london");
    driver.findElement(By.id("pv-contact-details-postcode")).sendKeys("nw1 2er");
    driver.findElement(By.id("pv-contact-details-post-check")).click();
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "23-Phone";
    driver.findElement(By.id("pv-phone-number-yes")).click();
    driver.findElement(By.name("pv-phone-number-yes")).sendKeys("0987654321");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "24-Consent";
    driver.findElement(By.id("co-operate-with-police-yes")).click();
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "26-FRDetails";
    driver.findElement(By.id("fr-details-first-name")).sendKeys("mary");
    driver.findElement(By.id("fr-details-last-name")).sendKeys("bennett");
    driver.findElement(By.id("fr-details-role")).sendKeys("caseworker");
    driver.findElement(By.id("fr-details-phone")).sendKeys("09372638483");
    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    screenName = "27-Alternate";
    driver.findElement(By.id("fr-alternative-contact")).click();
    driver.findElement(By.id("fr-alternative-contact")).sendKeys("alternate@info.com");
    Shutterbug.shootPage(driver).withName(screenName).save(imagePath);
    driver.findElement(By.cssSelector(".button")).click();
    
    //need to add the CYA screenshot, referral submission step and success page screenshot 
    //once defect 1030 is fixed
    System.out.println("Test completed");
   
    
  }
}