// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.assertthat.selenium_shutterbug.core.Shutterbug;
import com.assertthat.selenium_shutterbug.utils.web.ScrollStrategy;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class Register {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  //@Before
  //public void setUp() {
	//System.setProperty("webdriver.chrome.driver", "/Users/Bean/Desktop/Selenium/chromedriver");
    //driver = new ChromeDriver();
    //js = (JavascriptExecutor) driver;
    //vars = new HashMap<String, Object>();
  //}
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void register1() throws Exception {
	  String projectName = "MS_Test";
	  String screenName;
	  
	  	ExcelUtil.setExcelFile(ExcelUtil.Path_TestData + ExcelUtil.File_TestData, "registration");
		int columnLast = ExcelUtil.lastColumn;
		int rowNumbers = ExcelUtil.rowCount;
		System.out.println("rowcount " + rowNumbers + " last column " + columnLast + "test name" + "registration");
		//String columnResult = dateFormat.format(date);
		//ExcelUtil.setCellData(columnResult, 0, columnLast);
		
    
	  for(int line=1; line<=4; line++){
	    System.setProperty("webdriver.chrome.driver", "/Users/Bean/Desktop/Selenium/chromedriver");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();  
	    driver.get("https://uat.ms-notprod.homeoffice.gov.uk/start");
	    driver.manage().window().setSize(new Dimension(1440, 877));
	    String testName = "Register." + line;
	    String imagePath = ".." + ReferralEntry.fileSeparator + "Results_Screenshots" + ReferralEntry.fileSeparator + projectName + ReferralEntry.fileSeparator + ReferralEntry.dateFormat2.format(ReferralEntry.date) + ReferralEntry.fileSeparator + ReferralEntry.dateFormat3.format(ReferralEntry.date) + ReferralEntry.fileSeparator + testName;
	    
	    String suserorg = ExcelUtil.getCellData(line, 1);
		String semail = ExcelUtil.getCellData(line, 2);
	    
	    screenName = "1-landingpage";
	    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
	    driver.findElement(By.cssSelector(".button")).click();
	    
	    screenName = "2-register";
	    driver.findElement(By.id("user-organisation")).sendKeys(suserorg);
	    driver.findElement(By.id("user-email")).sendKeys(semail);
	    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
	    driver.findElement(By.cssSelector(".button")).click(); 
	    
	    screenName = "3-confirmemail";
	    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
	    driver.findElement(By.cssSelector(".button")).click();
	    
	    screenName = "4-confirmregister";
	    Shutterbug.shootPage(driver,ScrollStrategy.BOTH_DIRECTIONS,500,true).withName(screenName).save(imagePath);
	    driver.quit();
	  }
  }
}
